spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.91.144.191:1521:DASL3
    username: DASCORE_CM_VIVEK
    password: dascore
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
 
server:
  port: 8084
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/